"""phlebo, payment, address tables added

Revision ID: 1ebafecdeded
Revises: 
Create Date: 2018-12-09 19:11:26.379004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebafecdeded'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order_cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phlebo_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('phlebo_id', sa.Integer(), nullable=False),
    sa.Column('phlebo_name', sa.String(), nullable=True),
    sa.Column('phlebo_phone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phlebo_details')
    op.drop_table('order_details')
    op.drop_table('order_cart')
    # ### end Alembic commands ###
