"""phlebo, payment, address tables added

Revision ID: e2bab19eba1a
Revises: 1ebafecdeded
Create Date: 2018-12-09 19:43:00.916588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2bab19eba1a'
down_revision = '1ebafecdeded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_details', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'payment_details', 'order_cart', ['order_id'], ['id'])
    op.add_column('pickup_address', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pickup_address', 'order_cart', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pickup_address', type_='foreignkey')
    op.drop_column('pickup_address', 'order_id')
    op.drop_constraint(None, 'payment_details', type_='foreignkey')
    op.drop_column('payment_details', 'order_id')
    # ### end Alembic commands ###
